apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-generator
  namespace: challenge-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challenge-generator
  template:
    metadata:
      labels:
        app: challenge-generator
    spec:
      containers:
        - name: challenge-generator
          image: "celula.azurecr.io/challenge-generator"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: challenge-generator-secrets
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "500m"
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 3000
          #   initialDelaySeconds: 60
          #   periodSeconds: 10
          #   timeoutSeconds: 10
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     port: 3000
          #     path: /health
          #   initialDelaySeconds: 60
          #   periodSeconds: 10
          #   timeoutSeconds: 10
          #   failureThreshold: 3