apiVersion: v1
kind: Service
metadata:
  name: challenge-generator
  namespace: challenge-generator
  labels:
    app: challenge-generator
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: challenge-generator